### ISSUE TITLE
Crash after R8/Proguard

### ISSUE THREAD

**Issue by Nojipiz** [skydoves/retrofit-adapters#24] opened 2023-08-31 13:35 UTC
**Please complete the following information:**
- Library Version: 1.0.6
- Affected Device(s) All
 
**Describe the Bug:**

After minify the code with R8, can't use the library anymore, and throw an exception:

`java.lang.IllegalArgumentException: Unable to create call adapter for retrofit2.Call<arrow.core.Either>`

I have used the proguard rules described in Retrofit2 repository:

```
-keepattributes Signature, InnerClasses, EnclosingMethod, Exceptions, *Annotation*, AnnotationDefault, RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations, InnerClasses, Annotation
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}
-dontwarn javax.annotation.**
-dontwarn kotlin.Unit
-dontnote retrofit2.Platform
-dontwarn retrofit2.KotlinExtensions
-dontwarn retrofit2.KotlinExtensions$*

-if interface * { @retrofit2.http.* <methods>; }
-keep,allowobfuscation interface <1>

-if interface * { @retrofit2.http.* <methods>; }
-keep,allowobfuscation interface * extends <1>

-if interface * { @retrofit2.http.* public *** *(...); }
-keep,allowoptimization,allowshrinking,allowobfuscation class <3>

-keep,allowobfuscation,allowshrinking class retrofit2.Response
-keep,allowobfuscation,allowshrinking class kotlin.coroutines.Continuation
-keep,allowobfuscation,allowshrinking interface retrofit2.Call
```
According to the ArrowKt repository, it doesn't need extra rules in the proguard file.
Any idea of why this happen? 

**Expected Behavior:**

It should work normally.

**Comment by skydoves** [comment] 2023-08-31 14:35
Hey @Nojipiz, this is a known issue from OkHttp. This issue will be fixed in the next release. Thanks for creating this issue!

**Comment by skydoves** [comment] 2023-09-01 14:35
Hey @Nojipiz, 1.0.7 stable has been released. Thanks for the issue!

**Closed by skydoves** 2023-09-01 14:35 UTC

**Comment by nvkleban** [comment] 2024-07-19 02:23
@skydoves Crash still happens in latest version, can you add please consumer proguard rules with

```-keep,allowobfuscation,allowshrinking class arrow.core.Either```

[Source](https://github.com/square/retrofit/issues/3751#issuecomment-1525918774)

**Comment by PavlosTze** [comment] 2024-08-14 10:36
I agree with @nvkleban , the library keeps crashing. Can you please fix it @skydoves ?

**Comment by skydoves** [comment] 2024-08-14 10:45
Hey @PavlosTze do you also face the issue from the retrofit-adapter-arrow library?

**Comment by skydoves** [comment] 2024-08-14 10:48
@nvkleban 1.0.12 has been released and it contains the proguard rules itself.

**Comment by PavlosTze** [comment] 2024-08-14 10:49
Yes, I'm using the [EitherCallAdapterFactory](https://github.com/skydoves/retrofit-adapters?tab=readme-ov-file#eithercalladapterfactory), and I'm having constant crashes on the "Release" version (where Proguard is used - Debug version works OK).

As soon as I added the following line in Proguard the issue has been fixed:
` -keep,allowobfuscation,allowshrinking class arrow.core.Either`

I was getting a bit different error, although the cause (Proguard) was the same:

> Caused by java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
>        at com.skydoves.retrofit.adapters.arrow.EitherCallAdapterFactory.checkLeftIsThrowable(EitherCallAdapterFactory.kt:91)
>        at com.skydoves.retrofit.adapters.arrow.EitherCallAdapterFactory.get(EitherCallAdapterFactory.kt:58)

**Comment by HeyPouya** [comment] 2024-08-24 15:45
@skydoves Hi there 
I was getting the same error for the Result adapter in the release build.
Adding this line fixed it for me:

` -keep,allowobfuscation,allowshrinking class kotlin.Result
`

I'm using latest version of both retrofit and the adapter.

Here is the stack trace for your refrence:

`
                                                                                                    java.lang.IllegalArgumentException: Unable to create call adapter for retrofit2.Call<kotlin.Result>
                                                                                                        for method PhotosApiServices.getPhotos-gIAlu-s
                                                                                                    	at retrofit2.Utils.methodError(Utils.java:56)
                                                                                                    	at retrofit2.HttpServiceMethod.createCallAdapter(HttpServiceMethod.java:129)
                                                                                                    	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:78)
                                                                                                    	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
                                                                                                    	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:235)
                                                                                                    	at retrofit2.Retrofit$1.invoke(Retrofit.java:177)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy5.getPhotos-gIAlu-s(Unknown Source)
                                                                                                    	at com.akorayan.photos.data.datasourse.PhotosDataSourceImpl.getPhotos(PhotosDataSourceImpl.kt:46)
                                                                                                    	at com.akorayan.photos.data.repositoryimpl.PhotosRepositoryImpl$getPhotos$2.invokeSuspend(PhotosRepositoryImpl.kt:21)
                                                                                                    	at com.akorayan.photos.data.repositoryimpl.PhotosRepositoryImpl$getPhotos$2.invoke(PhotosRepositoryImpl.kt:0)
                                                                                                    	at com.akorayan.photos.data.repositoryimpl.PhotosRepositoryImpl$getPhotos$2.invoke(PhotosRepositoryImpl.kt:0)
                                                                                                    	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:57)
                                                                                                    	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:226)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:191)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:153)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt:0)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:56)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@967a7fa, Dispatchers.Main.immediate]
                                                                                                    Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
                                                                                                    	at com.skydoves.retrofit.adapters.result.ResultCallAdapterFactory.get(ResultCallAdapterFactory.kt:58)
                                                                                                    	at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:309)
                                                                                                    	at retrofit2.Retrofit.callAdapter(Retrofit.java:293)
                                                                                                    	at retrofit2.HttpServiceMethod.createCallAdapter(HttpServiceMethod.java:127)
`

**Comment by MahdiPorkar-github** [comment] 2024-12-10 10:42
I got the same error mentioned here by @HeyPouya
https://github.com/skydoves/retrofit-adapters/issues/24#issuecomment-2308435511

**Comment by rezazavvareh1993** [comment] 2024-12-10 21:47
Please fix this bug

**Comment by johnjohndoe** [comment] 2025-02-01 21:11
For me it worked when I added the following line to my ProGuard rules file:

```
-keep public class kotlin.Result { *; }
```

**Comment by skydoves** [comment] 2025-02-02 02:10
@johnjohndoe Thanks for sharing this solution! Let me include it in the library and will release the next version soon.
